development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:588c124ebe0d7046de3b57cdd1701f57@pike.redistogo.com:11513/
  
  channel_prefix: MessageMe_production
